(* DO NOT EDIT MANUALLY *)
(*  *)
(* generated by sqlgg 20231201-336-gecc0719 on 2026-06-10T07:39Z *)

module DbOps (T : Sqlgg_traits.M) = struct

  module IO = Sqlgg_io.Blocking

  let create_leagues db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS leagues (\n\
    id INTEGER PRIMARY KEY,\n\
    league_year INTEGER NOT NULL,\n\
    name TEXT NOT NULL\n\
)") T.no_params

  let add_league db ~id ~league_year ~name =
    let set_params stmt =
      let p = T.start_params stmt (3) in
      T.set_param_Int p id;
      T.set_param_Int p league_year;
      T.set_param_Text p name;
      T.finish_params p
    in
    T.execute db ("INSERT INTO leagues VALUES (@id,@league_year,@name)") set_params

  let leagues_for_year db ~year callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_year:(T.get_column_Int stmt 1)
        ~name:(T.get_column_Text stmt 2)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Int p year;
      T.finish_params p
    in
    T.select db ("SELECT * FROM leagues\n\
WHERE league_year == @year\n\
ORDER BY id") set_params invoke_callback

  let leagues_for_name db ~league_name callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_year:(T.get_column_Int stmt 1)
        ~name:(T.get_column_Text stmt 2)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Text p league_name;
      T.finish_params p
    in
    T.select db ("SELECT * FROM leagues\n\
WHERE name = @league_name\n\
ORDER BY id") set_params invoke_callback

  let all_leagues db  callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_year:(T.get_column_Int stmt 1)
        ~name:(T.get_column_Text stmt 2)
    in
    T.select db ("SELECT * FROM leagues ORDER BY league_year DESC, name DESC") T.no_params invoke_callback

  let create_league_events db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS league_events (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
\n\
    event_date TEXT NOT NULL,\n\
    location TEXT NOT NULL\n\
)") T.no_params

  let create_league_events_date_idx db  =
    T.execute db ("CREATE INDEX IF NOT EXISTS idx_league_events_date ON league_events(event_date DESC)") T.no_params

  let add_league_event db ~id ~league_id ~event_nr ~event_date ~location =
    let set_params stmt =
      let p = T.start_params stmt (5) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Text p event_date;
      T.set_param_Text p location;
      T.finish_params p
    in
    T.execute db ("INSERT INTO league_events VALUES (@id,@league_id,@event_nr,@event_date,@location)") set_params

  let create_event_details db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS event_details (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
\n\
    event_link TEXT NOT NULL,\n\
                event_date TEXT NOT NULL,\n\
    location TEXT NOT NULL,\n\
    thumbnail TEXT NOT NULL,\n\
    map_info TEXT NOT NULL\n\
)") T.no_params

  let create_event_details_date_idx db  =
    T.execute db ("CREATE INDEX IF NOT EXISTS idx_event_details_date ON event_details(event_date)") T.no_params

  let add_event_details db ~id ~event_link ~event_date ~location ~thumbnail ~map_info =
    let set_params stmt =
      let p = T.start_params stmt (6) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Text p event_link;
      T.set_param_Text p event_date;
      T.set_param_Text p location;
      T.set_param_Text p thumbnail;
      T.set_param_Text p map_info;
      T.finish_params p
    in
    T.execute db ("INSERT INTO event_details VALUES (@id,@event_link,@event_date,@location,@thumbnail,@map_info)") set_params

  let create_event_map_links db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS event_map_links (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
\n\
    event_date TEXT NOT NULL,\n\
        links TEXT NOT NULL\n\
)") T.no_params

  let create_event_map_links_date_idx db  =
    T.execute db ("CREATE INDEX IF NOT EXISTS idx_event_map_links_date ON event_map_links(event_date)") T.no_params

  let add_event_map_link db ~id ~event_date ~links =
    let set_params stmt =
      let p = T.start_params stmt (3) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Text p event_date;
      T.set_param_Text p links;
      T.finish_params p
    in
    T.execute db ("INSERT INTO event_map_links VALUES (@id,@event_date,@links)") set_params

  let league_event_neighbors db ~input_date callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_id:(T.get_column_Int stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~event_date:(T.get_column_Text stmt 3)
        ~location:(T.get_column_Text stmt 4)
        ~league_name:(T.get_column_Text stmt 5)
        ~event_link:(T.get_column_Text_nullable stmt 6)
        ~thumbnail:(T.get_column_Text_nullable stmt 7)
        ~map_info:(T.get_column_Text_nullable stmt 8)
        ~official_location:(T.get_column_Text_nullable stmt 9)
        ~links:(T.get_column_Text_nullable stmt 10)
    in
    let set_params stmt =
      let p = T.start_params stmt (2) in
      T.set_param_Text p input_date;
      T.set_param_Text p input_date;
      T.finish_params p
    in
    T.select db ("WITH base AS (\n\
    SELECT \n\
        le.*,\n\
        l.name        AS league_name,\n\
        ed.event_link,\n\
        ed.thumbnail,\n\
        ed.map_info,\n\
        ed.location AS official_location,\n\
        ls.links\n\
    FROM league_events le\n\
    JOIN leagues          l  ON le.league_id  = l.id\n\
    LEFT JOIN event_details   ed ON le.event_date = ed.event_date\n\
    LEFT JOIN event_map_links ls ON le.event_date = ls.event_date\n\
),\n\
before AS (\n\
    SELECT *\n\
    FROM base\n\
    WHERE event_date < @input_date\n\
    ORDER BY event_date DESC\n\
    LIMIT 1\n\
),\n\
after_or_eq AS (\n\
    SELECT *\n\
    FROM base\n\
    WHERE event_date >= @input_date\n\
    ORDER BY event_date ASC\n\
    LIMIT 1\n\
)\n\
SELECT * FROM before\n\
UNION ALL\n\
SELECT * FROM after_or_eq") set_params invoke_callback

  let event_details_for_year db ~year callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~event_link:(T.get_column_Text stmt 1)
        ~event_date:(T.get_column_Text stmt 2)
        ~location:(T.get_column_Text stmt 3)
        ~thumbnail:(T.get_column_Text stmt 4)
        ~map_info:(T.get_column_Text stmt 5)
        ~links:(T.get_column_Text_nullable stmt 6)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Text p year;
      T.finish_params p
    in
    T.select db ("SELECT \n\
    e.*,\n\
    l.links\n\
FROM event_details e\n\
LEFT JOIN event_map_links l\n\
ON e.event_date = l.event_date\n\
WHERE strftime('%Y', e.event_date) == @year\n\
ORDER BY e.event_date ASC") set_params invoke_callback

  let event_details_for_date db ~event_date callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~event_link:(T.get_column_Text stmt 1)
        ~event_date:(T.get_column_Text stmt 2)
        ~location:(T.get_column_Text stmt 3)
        ~thumbnail:(T.get_column_Text stmt 4)
        ~map_info:(T.get_column_Text stmt 5)
        ~links:(T.get_column_Text_nullable stmt 6)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Text p event_date;
      T.finish_params p
    in
    T.select db ("SELECT \n\
    e.*,\n\
    l.links\n\
FROM event_details e\n\
LEFT JOIN event_map_links l\n\
ON e.event_date = l.event_date\n\
WHERE e.event_date == @event_date") set_params invoke_callback

  let create_event_maps db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS event_maps (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
\n\
    event_date TEXT NOT NULL,\n\
    map_key TEXT NOT NULL,\n\
    title TEXT NOT NULL,\n\
    default_map_img TEXT NOT NULL,\n\
    bike_map_img TEXT DEFAULT NULL,\n\
    lat FLOAT NOT NULL,\n\
    lon FLOAT NOT NULL\n\
)") T.no_params

  let create_event_maps_date_idx db  =
    T.execute db ("CREATE INDEX IF NOT EXISTS idx_event_maps_date ON event_maps(event_date DESC)") T.no_params

  let add_event_map db ~id ~event_date ~map_key ~title ~default_map_img ~bike_map_img ~lat ~lon =
    let set_params stmt =
      let p = T.start_params stmt (8) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Text p event_date;
      T.set_param_Text p map_key;
      T.set_param_Text p title;
      T.set_param_Text p default_map_img;
      begin match bike_map_img with None -> T.set_param_null p | Some v -> T.set_param_Text p v end;
      T.set_param_Float p lat;
      T.set_param_Float p lon;
      T.finish_params p
    in
    T.execute db ("INSERT INTO event_maps VALUES (@id,@event_date,@map_key,@title,@default_map_img,@bike_map_img,@lat,@lon)") set_params

  let create_event_stats db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS event_stats (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    event_date TEXT NOT NULL,\n\
\n\
    num_men INTEGER NOT NULL,\n\
    num_women INTEGER NOT NULL\n\
)") T.no_params

  let add_event_stats db ~id ~league_id ~event_nr ~event_date ~num_men ~num_women =
    let set_params stmt =
      let p = T.start_params stmt (6) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Text p event_date;
      T.set_param_Int p num_men;
      T.set_param_Int p num_women;
      T.finish_params p
    in
    T.execute db ("INSERT INTO event_stats VALUES (@id,@league_id,@event_nr,@event_date,@num_men,@num_women)") set_params

  let events_to_be_processed db  callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_id:(T.get_column_Int stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~event_date:(T.get_column_Text stmt 3)
        ~location:(T.get_column_Text stmt 4)
    in
    T.select db ("SELECT le.*\n\
FROM league_events le\n\
LEFT JOIN event_stats es ON le.event_date = es.event_date\n\
WHERE es.id IS NULL\n\
ORDER BY \n\
    le.league_id ASC, \n\
    le.event_date ASC") T.no_params invoke_callback

  let events_to_be_processed_for_year db ~league_year callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_id:(T.get_column_Int stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~event_date:(T.get_column_Text stmt 3)
        ~location:(T.get_column_Text stmt 4)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Int p league_year;
      T.finish_params p
    in
    T.select db ("SELECT le.*\n\
FROM league_events le\n\
JOIN leagues l ON le.league_id = l.id\n\
LEFT JOIN event_stats es ON le.event_date = es.event_date\n\
WHERE l.league_year = @league_year\n\
  AND es.id IS NULL\n\
ORDER BY \n\
    le.league_id ASC, \n\
    le.event_date ASC") set_params invoke_callback

  let create_courses db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS courses (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    event_date TEXT NOT NULL,\n\
    course_id TEXT NOT NULL,\n\
\n\
    distance FLOAT NOT NULL,\n\
    num_controls INTEGER NOT NULL,\n\
    controls TEXT NOT NULL\n\
)") T.no_params

  let add_course db ~id ~league_id ~event_nr ~event_date ~course_id ~distance ~num_controls ~controls =
    let set_params stmt =
      let p = T.start_params stmt (8) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Text p event_date;
      T.set_param_Text p course_id;
      T.set_param_Float p distance;
      T.set_param_Int p num_controls;
      T.set_param_Text p controls;
      T.finish_params p
    in
    T.execute db ("INSERT INTO courses VALUES (@id,@league_id,@event_nr,@event_date,@course_id,@distance,@num_controls,@controls)") set_params

  let courses_for_event db ~event_date callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_id:(T.get_column_Int stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~event_date:(T.get_column_Text stmt 3)
        ~course_id:(T.get_column_Text stmt 4)
        ~distance:(T.get_column_Float stmt 5)
        ~num_controls:(T.get_column_Int stmt 6)
        ~controls:(T.get_column_Text stmt 7)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Text p event_date;
      T.finish_params p
    in
    T.select db ("SELECT * FROM courses \n\
WHERE event_date = @event_date\n\
ORDER BY course_id ASC") set_params invoke_callback

  let create_course_stats db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS course_stats (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    event_date TEXT NOT NULL,\n\
    course_id TEXT NOT NULL,\n\
\n\
    num_men  INTEGER NOT NULL,\n\
    num_women  INTEGER NOT NULL,\n\
    tilt_overall  INTEGER NOT NULL,\n\
    tilt_men  INTEGER NOT NULL,\n\
    tilt_women  INTEGER NOT NULL,\n\
    mistake_time_overall  INTEGER NOT NULL,\n\
    mistake_time_men  INTEGER NOT NULL,\n\
    mistake_time_women  INTEGER NOT NULL,\n\
    blunder_perc_overall  INTEGER NOT NULL,\n\
    blunder_perc_men  INTEGER NOT NULL,\n\
    blunder_perc_women  INTEGER NOT NULL,\n\
    big_mistake_perc_overall  INTEGER NOT NULL,\n\
    big_mistake_perc_men  INTEGER NOT NULL,\n\
    big_mistake_perc_women  INTEGER NOT NULL,\n\
    small_mistake_perc_overall  INTEGER NOT NULL,\n\
    small_mistake_perc_men  INTEGER NOT NULL,\n\
    small_mistake_perc_women  INTEGER NOT NULL,\n\
    most_tricky_overall  INTEGER DEFAULT NULL,\n\
    most_tricky_men  INTEGER DEFAULT NULL,\n\
    most_tricky_women  INTEGER DEFAULT NULL,\n\
    avg_time_for_mistake_overall  INTEGER NOT NULL,\n\
    avg_time_for_mistake_men  INTEGER NOT NULL,\n\
    avg_time_for_mistake_women  INTEGER NOT NULL,\n\
    avg_mistake_num_overall  INTEGER NOT NULL,\n\
    avg_mistake_num_men  INTEGER NOT NULL,\n\
    avg_mistake_num_women  INTEGER NOT NULL\n\
)") T.no_params

  let add_course_stats db ~id ~league_id ~event_nr ~event_date ~course_id ~num_men ~num_women ~tilt_overall ~tilt_men ~tilt_women ~mistake_time_overall ~mistake_time_men ~mistake_time_women ~blunder_perc_overall ~blunder_perc_men ~blunder_perc_women ~big_mistake_perc_overall ~big_mistake_perc_men ~big_mistake_perc_women ~small_mistake_perc_overall ~small_mistake_perc_men ~small_mistake_perc_women ~most_tricky_overall ~most_tricky_men ~most_tricky_women ~avg_time_for_mistake_overall ~avg_time_for_mistake_men ~avg_time_for_mistake_women ~avg_mistake_num_overall ~avg_mistake_num_men ~avg_mistake_num_women =
    let set_params stmt =
      let p = T.start_params stmt (31) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Text p event_date;
      T.set_param_Text p course_id;
      T.set_param_Int p num_men;
      T.set_param_Int p num_women;
      T.set_param_Int p tilt_overall;
      T.set_param_Int p tilt_men;
      T.set_param_Int p tilt_women;
      T.set_param_Int p mistake_time_overall;
      T.set_param_Int p mistake_time_men;
      T.set_param_Int p mistake_time_women;
      T.set_param_Int p blunder_perc_overall;
      T.set_param_Int p blunder_perc_men;
      T.set_param_Int p blunder_perc_women;
      T.set_param_Int p big_mistake_perc_overall;
      T.set_param_Int p big_mistake_perc_men;
      T.set_param_Int p big_mistake_perc_women;
      T.set_param_Int p small_mistake_perc_overall;
      T.set_param_Int p small_mistake_perc_men;
      T.set_param_Int p small_mistake_perc_women;
      begin match most_tricky_overall with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      begin match most_tricky_men with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      begin match most_tricky_women with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p avg_time_for_mistake_overall;
      T.set_param_Int p avg_time_for_mistake_men;
      T.set_param_Int p avg_time_for_mistake_women;
      T.set_param_Int p avg_mistake_num_overall;
      T.set_param_Int p avg_mistake_num_men;
      T.set_param_Int p avg_mistake_num_women;
      T.finish_params p
    in
    T.execute db ("INSERT INTO course_stats VALUES (@id,@league_id,@event_nr,@event_date,@course_id,@num_men,@num_women,@tilt_overall,@tilt_men,@tilt_women,@mistake_time_overall,@mistake_time_men,@mistake_time_women,@blunder_perc_overall,@blunder_perc_men,@blunder_perc_women,@big_mistake_perc_overall,@big_mistake_perc_men,@big_mistake_perc_women,@small_mistake_perc_overall,@small_mistake_perc_men,@small_mistake_perc_women,@most_tricky_overall,@most_tricky_men,@most_tricky_women,@avg_time_for_mistake_overall,@avg_time_for_mistake_men,@avg_time_for_mistake_women,@avg_mistake_num_overall,@avg_mistake_num_men,@avg_mistake_num_women)") set_params

  let stats_for_course db ~league_id ~event_date ~course_id callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_id:(T.get_column_Int stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~event_date:(T.get_column_Text stmt 3)
        ~course_id:(T.get_column_Text stmt 4)
        ~num_men:(T.get_column_Int stmt 5)
        ~num_women:(T.get_column_Int stmt 6)
        ~tilt_overall:(T.get_column_Int stmt 7)
        ~tilt_men:(T.get_column_Int stmt 8)
        ~tilt_women:(T.get_column_Int stmt 9)
        ~mistake_time_overall:(T.get_column_Int stmt 10)
        ~mistake_time_men:(T.get_column_Int stmt 11)
        ~mistake_time_women:(T.get_column_Int stmt 12)
        ~blunder_perc_overall:(T.get_column_Int stmt 13)
        ~blunder_perc_men:(T.get_column_Int stmt 14)
        ~blunder_perc_women:(T.get_column_Int stmt 15)
        ~big_mistake_perc_overall:(T.get_column_Int stmt 16)
        ~big_mistake_perc_men:(T.get_column_Int stmt 17)
        ~big_mistake_perc_women:(T.get_column_Int stmt 18)
        ~small_mistake_perc_overall:(T.get_column_Int stmt 19)
        ~small_mistake_perc_men:(T.get_column_Int stmt 20)
        ~small_mistake_perc_women:(T.get_column_Int stmt 21)
        ~most_tricky_overall:(T.get_column_Int_nullable stmt 22)
        ~most_tricky_men:(T.get_column_Int_nullable stmt 23)
        ~most_tricky_women:(T.get_column_Int_nullable stmt 24)
        ~avg_time_for_mistake_overall:(T.get_column_Int stmt 25)
        ~avg_time_for_mistake_men:(T.get_column_Int stmt 26)
        ~avg_time_for_mistake_women:(T.get_column_Int stmt 27)
        ~avg_mistake_num_overall:(T.get_column_Int stmt 28)
        ~avg_mistake_num_men:(T.get_column_Int stmt 29)
        ~avg_mistake_num_women:(T.get_column_Int stmt 30)
    in
    let set_params stmt =
      let p = T.start_params stmt (3) in
      T.set_param_Int p league_id;
      T.set_param_Text p event_date;
      T.set_param_Text p course_id;
      T.finish_params p
    in
    T.select db ("SELECT * FROM course_stats\n\
WHERE league_id = @league_id\n\
    AND event_date = @event_date\n\
    AND course_id = @course_id") set_params invoke_callback

  let create_age_groups db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS age_groups (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    runner_id INTEGER NOT NULL,\n\
\n\
    age_group_id TEXT NOT NULL\n\
)") T.no_params

  let add_age_group_for_runner db ~id ~league_id ~runner_id ~age_group_id =
    let set_params stmt =
      let p = T.start_params stmt (4) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p runner_id;
      T.set_param_Text p age_group_id;
      T.finish_params p
    in
    T.execute db ("INSERT INTO age_groups VALUES (@id,@league_id,@runner_id,@age_group_id)") set_params

  let all_groups db  callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_id:(T.get_column_Int stmt 1)
        ~runner_id:(T.get_column_Int stmt 2)
        ~age_group_id:(T.get_column_Text stmt 3)
    in
    T.select db ("SELECT * FROM age_groups") T.no_params invoke_callback

  let create_results db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS results (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    event_date TEXT NOT NULL,\n\
    course_id TEXT NOT NULL,\n\
    runner_id INTEGER NOT NULL,\n\
\n\
    time_sec INTEGER DEFAULT NULL,\n\
    start_time INTEGER DEFAULT NULL,\n\
    points INTEGER NOT NULL,\n\
    pace TEXT DEFAULT NULL,\n\
    dsq INTEGER NOT NULL\n\
)") T.no_params

  let results_for_course db ~league_id ~event_date ~course_id callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_id:(T.get_column_Int stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~event_date:(T.get_column_Text stmt 3)
        ~course_id:(T.get_column_Text stmt 4)
        ~runner_id:(T.get_column_Int stmt 5)
        ~time_sec:(T.get_column_Int_nullable stmt 6)
        ~start_time:(T.get_column_Int_nullable stmt 7)
        ~points:(T.get_column_Int stmt 8)
        ~pace:(T.get_column_Text_nullable stmt 9)
        ~dsq:(T.get_column_Int stmt 10)
    in
    let set_params stmt =
      let p = T.start_params stmt (3) in
      T.set_param_Int p league_id;
      T.set_param_Text p event_date;
      T.set_param_Text p course_id;
      T.finish_params p
    in
    T.select db ("SELECT * FROM results\n\
WHERE league_id = @league_id\n\
    AND event_date = @event_date\n\
    AND course_id = @course_id\n\
ORDER BY\n\
    dsq ASC,\n\
    time_sec ASC") set_params invoke_callback

  let add_result db ~id ~league_id ~event_nr ~event_date ~course_id ~runner_id ~time_sec ~start_time ~points ~pace ~dsq =
    let set_params stmt =
      let p = T.start_params stmt (11) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Text p event_date;
      T.set_param_Text p course_id;
      T.set_param_Int p runner_id;
      begin match time_sec with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      begin match start_time with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p points;
      begin match pace with None -> T.set_param_null p | Some v -> T.set_param_Text p v end;
      T.set_param_Int p dsq;
      T.finish_params p
    in
    T.execute db ("INSERT INTO results VALUES (@id,@league_id,@event_nr,@event_date,@course_id,@runner_id,@time_sec,@start_time,@points,@pace,@dsq)") set_params

  let create_result_stats db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS result_stats (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    event_date TEXT NOT NULL,\n\
    course_id TEXT NOT NULL,\n\
    runner_id INTEGER NOT NULL,\n\
\n\
    mistake_time INTEGER NOT NULL,\n\
    mistake_num INTEGER NOT NULL,\n\
\n\
    small_mistake_time INTEGER NOT NULL,\n\
    small_mistake_num INTEGER NOT NULL,\n\
    small_mistake_time_ratio INTEGER NOT NULL,\n\
    small_mistake_num_ratio INTEGER NOT NULL,\n\
\n\
    big_mistake_time INTEGER NOT NULL,\n\
    big_mistake_num INTEGER NOT NULL,\n\
    big_mistake_time_ratio INTEGER NOT NULL,\n\
    big_mistake_num_ratio INTEGER NOT NULL,\n\
\n\
    blunder_mistake_time INTEGER NOT NULL,\n\
    blunder_mistake_num INTEGER NOT NULL,\n\
    blunder_mistake_time_ratio INTEGER NOT NULL,\n\
    blunder_mistake_num_ratio INTEGER NOT NULL,\n\
\n\
    consecutive_mistakes INTEGER NOT NULL,\n\
    tilt_rate INTEGER NOT NULL,\n\
\n\
    mistake_cluster TEXT DEFAULT NULL,\n\
    mistakes_impact TEXT DEFAULT NULL,\n\
    race_execution TEXT DEFAULT NULL,\n\
\n\
    best_splits INTEGER NOT NULL,\n\
    top5_splits INTEGER NOT NULL,\n\
    top10_splits INTEGER NOT NULL,\n\
    performance INTEGER NOT NULL,\n\
\n\
    overall_position INTEGER DEFAULT NULL,\n\
    position_gender INTEGER DEFAULT NULL,\n\
    position_group INTEGER DEFAULT NULL,\n\
\n\
    potential_time INTEGER DEFAULT NULL,\n\
    potential_position INTEGER DEFAULT NULL\n\
)") T.no_params

  let add_result_stats db ~id ~league_id ~event_nr ~event_date ~course_id ~runner_id ~mistake_time ~mistake_num ~small_mistake_time ~small_mistake_num ~small_mistake_time_ratio ~small_mistake_num_ratio ~big_mistake_time ~big_mistake_num ~big_mistake_time_ratio ~big_mistake_num_ratio ~blunder_mistake_time ~blunder_mistake_num ~blunder_mistake_time_ratio ~blunder_mistake_num_ratio ~consecutive_mistakes ~tilt_rate ~mistake_cluster ~mistakes_impact ~race_execution ~best_splits ~top5_splits ~top10_splits ~performance ~overall_position ~position_gender ~position_group ~potential_time ~potential_position =
    let set_params stmt =
      let p = T.start_params stmt (34) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Text p event_date;
      T.set_param_Text p course_id;
      T.set_param_Int p runner_id;
      T.set_param_Int p mistake_time;
      T.set_param_Int p mistake_num;
      T.set_param_Int p small_mistake_time;
      T.set_param_Int p small_mistake_num;
      T.set_param_Int p small_mistake_time_ratio;
      T.set_param_Int p small_mistake_num_ratio;
      T.set_param_Int p big_mistake_time;
      T.set_param_Int p big_mistake_num;
      T.set_param_Int p big_mistake_time_ratio;
      T.set_param_Int p big_mistake_num_ratio;
      T.set_param_Int p blunder_mistake_time;
      T.set_param_Int p blunder_mistake_num;
      T.set_param_Int p blunder_mistake_time_ratio;
      T.set_param_Int p blunder_mistake_num_ratio;
      T.set_param_Int p consecutive_mistakes;
      T.set_param_Int p tilt_rate;
      begin match mistake_cluster with None -> T.set_param_null p | Some v -> T.set_param_Text p v end;
      begin match mistakes_impact with None -> T.set_param_null p | Some v -> T.set_param_Text p v end;
      begin match race_execution with None -> T.set_param_null p | Some v -> T.set_param_Text p v end;
      T.set_param_Int p best_splits;
      T.set_param_Int p top5_splits;
      T.set_param_Int p top10_splits;
      T.set_param_Int p performance;
      begin match overall_position with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      begin match position_gender with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      begin match position_group with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      begin match potential_time with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      begin match potential_position with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.finish_params p
    in
    T.execute db ("INSERT INTO result_stats VALUES (@id,@league_id,@event_nr,@event_date,@course_id,@runner_id,@mistake_time,@mistake_num,@small_mistake_time,@small_mistake_num,@small_mistake_time_ratio,@small_mistake_num_ratio,@big_mistake_time,@big_mistake_num,@big_mistake_time_ratio,@big_mistake_num_ratio,@blunder_mistake_time,@blunder_mistake_num,@blunder_mistake_time_ratio,@blunder_mistake_num_ratio,@consecutive_mistakes,@tilt_rate,@mistake_cluster,@mistakes_impact,@race_execution,@best_splits,@top5_splits,@top10_splits,@performance,@overall_position,@position_gender,@position_group,@potential_time,@potential_position)") set_params

  let create_splits db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS splits (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    event_date TEXT NOT NULL,\n\
    course_id TEXT NOT NULL,\n\
    runner_id INTEGER NOT NULL,\n\
    split_idx INTEGER NOT NULL,\n\
\n\
    time_sec INTEGER DEFAULT NULL,\n\
    position INTEGER DEFAULT NULL,\n\
    overall_time INTEGER DEFAULT NULL,\n\
    overall_position INTEGER DEFAULT NULL,\n\
    split_timestamp INTEGER DEFAULT NULL,\n\
    mistake_time INTEGER DEFAULT NULL\n\
)") T.no_params

  let add_splits db ~id ~league_id ~event_nr ~event_date ~course_id ~runner_id ~split_idx ~time_sec ~position ~overall_time ~overall_position ~split_timestamp ~mistake_time =
    let set_params stmt =
      let p = T.start_params stmt (13) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Text p event_date;
      T.set_param_Text p course_id;
      T.set_param_Int p runner_id;
      T.set_param_Int p split_idx;
      begin match time_sec with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      begin match position with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      begin match overall_time with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      begin match overall_position with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      begin match split_timestamp with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      begin match mistake_time with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.finish_params p
    in
    T.execute db ("INSERT INTO splits VALUES (@id,@league_id,@event_nr,@event_date,@course_id,@runner_id,@split_idx,@time_sec,@position,@overall_time,@overall_position,@split_timestamp,@mistake_time)") set_params

  let create_runners db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS runners (\n\
    id INTEGER PRIMARY KEY,\n\
    join_date TEXT NOT NULL,\n\
    name TEXT NOT NULL,\n\
    club TEXT NOT NULL,\n\
    gender TEXT NOT NULL\n\
)") T.no_params

  let add_runner db ~id ~join_date ~name ~club ~gender =
    let set_params stmt =
      let p = T.start_params stmt (5) in
      T.set_param_Int p id;
      T.set_param_Text p join_date;
      T.set_param_Text p name;
      T.set_param_Text p club;
      T.set_param_Text p gender;
      T.finish_params p
    in
    T.execute db ("INSERT INTO runners VALUES (@id,@join_date,@name,@club,@gender)") set_params

  let all_runners db  callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~join_date:(T.get_column_Text stmt 1)
        ~name:(T.get_column_Text stmt 2)
        ~club:(T.get_column_Text stmt 3)
        ~gender:(T.get_column_Text stmt 4)
    in
    T.select db ("SELECT * FROM runners") T.no_params invoke_callback

  let create_ratings db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS ratings (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    event_date TEXT NOT NULL,\n\
    course_id TEXT NOT NULL,\n\
    runner_id INTEGER NOT NULL,\n\
\n\
    rating FLOAT NOT NULL,\n\
    rating_diff FLOAT NOT NULL,\n\
    rd FLOAT NOT NULL,\n\
    vol FLOAT NOT NULL\n\
)") T.no_params

  let ratings_for_course db ~course_id callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_id:(T.get_column_Int stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~event_date:(T.get_column_Text stmt 3)
        ~course_id:(T.get_column_Text stmt 4)
        ~runner_id:(T.get_column_Int stmt 5)
        ~rating:(T.get_column_Float stmt 6)
        ~rating_diff:(T.get_column_Float stmt 7)
        ~rd:(T.get_column_Float stmt 8)
        ~vol:(T.get_column_Float stmt 9)
        ~runner_name:(T.get_column_Text stmt 10)
        ~runner_club:(T.get_column_Text stmt 11)
        ~runner_gender:(T.get_column_Text stmt 12)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Text p course_id;
      T.finish_params p
    in
    T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
INNER JOIN (\n\
            SELECT runner_id, MAX(event_date) AS max_date\n\
    FROM ratings\n\
    GROUP BY runner_id\n\
) latest ON r.runner_id = latest.runner_id AND r.event_date = latest.max_date\n\
WHERE r.course_id = @course_id\n\
ORDER BY r.rating DESC") set_params invoke_callback

  let all_latest_ratings db  callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_id:(T.get_column_Int stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~event_date:(T.get_column_Text stmt 3)
        ~course_id:(T.get_column_Text stmt 4)
        ~runner_id:(T.get_column_Int stmt 5)
        ~rating:(T.get_column_Float stmt 6)
        ~rating_diff:(T.get_column_Float stmt 7)
        ~rd:(T.get_column_Float stmt 8)
        ~vol:(T.get_column_Float stmt 9)
        ~runner_name:(T.get_column_Text stmt 10)
        ~runner_club:(T.get_column_Text stmt 11)
        ~runner_gender:(T.get_column_Text stmt 12)
    in
    T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
INNER JOIN (\n\
            SELECT runner_id, MAX(event_date) AS max_date\n\
    FROM ratings\n\
    GROUP BY runner_id\n\
) latest ON r.runner_id = latest.runner_id AND r.event_date = latest.max_date") T.no_params invoke_callback

  let ratings_for_course_by_gender db ~gender ~course_id callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_id:(T.get_column_Int stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~event_date:(T.get_column_Text stmt 3)
        ~course_id:(T.get_column_Text stmt 4)
        ~runner_id:(T.get_column_Int stmt 5)
        ~rating:(T.get_column_Float stmt 6)
        ~rating_diff:(T.get_column_Float stmt 7)
        ~rd:(T.get_column_Float stmt 8)
        ~vol:(T.get_column_Float stmt 9)
        ~runner_name:(T.get_column_Text stmt 10)
        ~runner_club:(T.get_column_Text stmt 11)
        ~runner_gender:(T.get_column_Text stmt 12)
    in
    let set_params stmt =
      let p = T.start_params stmt (2) in
      T.set_param_Text p gender;
      T.set_param_Text p course_id;
      T.finish_params p
    in
    T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
INNER JOIN (\n\
            SELECT runner_id, MAX(event_date) AS max_date\n\
    FROM ratings\n\
    GROUP BY runner_id\n\
) latest ON r.runner_id = latest.runner_id AND r.event_date = latest.max_date\n\
INNER JOIN runners rn ON r.runner_id = rn.id\n\
WHERE rn.gender = @gender AND r.course_id = @course_id\n\
ORDER BY r.rating DESC") set_params invoke_callback

  let rating_history_for_league_and_course db ~runner_id ~league_id ~course_id callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_id:(T.get_column_Int stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~event_date:(T.get_column_Text stmt 3)
        ~course_id:(T.get_column_Text stmt 4)
        ~runner_id:(T.get_column_Int stmt 5)
        ~rating:(T.get_column_Float stmt 6)
        ~rating_diff:(T.get_column_Float stmt 7)
        ~rd:(T.get_column_Float stmt 8)
        ~vol:(T.get_column_Float stmt 9)
        ~runner_name:(T.get_column_Text stmt 10)
        ~runner_club:(T.get_column_Text stmt 11)
        ~runner_gender:(T.get_column_Text stmt 12)
    in
    let set_params stmt =
      let p = T.start_params stmt (3) in
      T.set_param_Int p runner_id;
      T.set_param_Int p league_id;
      T.set_param_Text p course_id;
      T.finish_params p
    in
    T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
WHERE runner_id = @runner_id \n\
    AND league_id = @league_id \n\
    AND course_id = @course_id\n\
ORDER BY event_date ASC") set_params invoke_callback

  let rating_history_for_course db ~runner_id ~course_id callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_id:(T.get_column_Int stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~event_date:(T.get_column_Text stmt 3)
        ~course_id:(T.get_column_Text stmt 4)
        ~runner_id:(T.get_column_Int stmt 5)
        ~rating:(T.get_column_Float stmt 6)
        ~rating_diff:(T.get_column_Float stmt 7)
        ~rd:(T.get_column_Float stmt 8)
        ~vol:(T.get_column_Float stmt 9)
        ~runner_name:(T.get_column_Text stmt 10)
        ~runner_club:(T.get_column_Text stmt 11)
        ~runner_gender:(T.get_column_Text stmt 12)
    in
    let set_params stmt =
      let p = T.start_params stmt (2) in
      T.set_param_Int p runner_id;
      T.set_param_Text p course_id;
      T.finish_params p
    in
    T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
WHERE runner_id = @runner_id \n\
    AND course_id = @course_id\n\
ORDER BY event_date ASC") set_params invoke_callback

  let add_rating db ~id ~league_id ~event_nr ~event_date ~course_id ~runner_id ~rating ~rating_diff ~rd ~vol =
    let set_params stmt =
      let p = T.start_params stmt (10) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Text p event_date;
      T.set_param_Text p course_id;
      T.set_param_Int p runner_id;
      T.set_param_Float p rating;
      T.set_param_Float p rating_diff;
      T.set_param_Float p rd;
      T.set_param_Float p vol;
      T.finish_params p
    in
    T.execute db ("INSERT INTO ratings VALUES (@id,@league_id,@event_nr,@event_date,@course_id,@runner_id,@rating,@rating_diff,@rd,@vol)") set_params

  let create_medals db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS medals (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    event_date TEXT NOT NULL,\n\
    course_id TEXT NOT NULL,\n\
    runner_id INTEGER NOT NULL,\n\
    medal_type TEXT NOT NULL CHECK (medal_type IN ('gold', 'silver', 'bronze'))\n\
)") T.no_params

  let add_medal db ~id ~league_id ~event_nr ~event_date ~course_id ~runner_id ~medal_type =
    let set_params stmt =
      let p = T.start_params stmt (7) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Text p event_date;
      T.set_param_Text p course_id;
      T.set_param_Int p runner_id;
      T.set_param_Text p medal_type;
      T.finish_params p
    in
    T.execute db ("INSERT INTO medals VALUES (@id,@league_id,@event_nr,@event_date,@course_id,@runner_id,@medal_type)") set_params

  let medals_for_runner_for_league db ~runner_id ~league_id =
    let get_row stmt =
      (T.get_column_Text stmt 0), (T.get_column_Int_nullable stmt 1), (T.get_column_Int_nullable stmt 2), (T.get_column_Int_nullable stmt 3)
    in
    let set_params stmt =
      let p = T.start_params stmt (2) in
      T.set_param_Int p runner_id;
      T.set_param_Int p league_id;
      T.finish_params p
    in
    T.select_one db ("SELECT \n\
    l.name AS league_name,\n\
\n\
    SUM(CASE WHEN rm.medal_type = 'gold' THEN 1 ELSE 0 END) AS gold_count,\n\
    SUM(CASE WHEN rm.medal_type = 'silver' THEN 1 ELSE 0 END) AS silver_count,\n\
    SUM(CASE WHEN rm.medal_type = 'bronze' THEN 1 ELSE 0 END) AS bronze_count\n\
\n\
FROM medals rm\n\
JOIN league_events le ON rm.event_date = le.event_date\n\
JOIN leagues l ON le.league_id = l.id\n\
WHERE rm.runner_id = @runner_id AND l.id = @league_id") set_params get_row

  let medals_for_runner_overall db ~runner_id =
    let get_row stmt =
      (T.get_column_Int_nullable stmt 0), (T.get_column_Int_nullable stmt 1), (T.get_column_Int_nullable stmt 2)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Int p runner_id;
      T.finish_params p
    in
    T.select_one db ("SELECT \n\
    SUM(CASE WHEN medal_type = 'gold' THEN 1 ELSE 0 END) AS gold,\n\
    SUM(CASE WHEN medal_type = 'silver' THEN 1 ELSE 0 END) AS silver,\n\
    SUM(CASE WHEN medal_type = 'bronze' THEN 1 ELSE 0 END) AS bronze\n\
FROM medals\n\
WHERE runner_id = @runner_id") set_params get_row

  let medal_history_for_runner db ~runner_id callback =
    let invoke_callback stmt =
      callback
        ~medal_type:(T.get_column_Text stmt 0)
        ~event_date:(T.get_column_Text stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~league_name:(T.get_column_Text stmt 3)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Int p runner_id;
      T.finish_params p
    in
    T.select db ("SELECT \n\
    rm.medal_type,\n\
    le.event_date,\n\
    le.event_nr,\n\
    l.name AS league_name\n\
FROM medals rm\n\
JOIN league_events le ON rm.event_date = le.event_date\n\
JOIN leagues l ON le.league_id = l.id\n\
WHERE rm.runner_id = @runner_id\n\
ORDER BY le.event_date ASC") set_params invoke_callback

  module Single = struct
    let medals_for_runner_for_league db ~runner_id ~league_id callback =
      let invoke_callback stmt =
        callback
          ~league_name:(T.get_column_Text stmt 0)
          ~gold_count:(T.get_column_Int_nullable stmt 1)
          ~silver_count:(T.get_column_Int_nullable stmt 2)
          ~bronze_count:(T.get_column_Int_nullable stmt 3)
      in
      let set_params stmt =
        let p = T.start_params stmt (2) in
        T.set_param_Int p runner_id;
        T.set_param_Int p league_id;
        T.finish_params p
      in
      T.select_one db ("SELECT \n\
    l.name AS league_name,\n\
\n\
    SUM(CASE WHEN rm.medal_type = 'gold' THEN 1 ELSE 0 END) AS gold_count,\n\
    SUM(CASE WHEN rm.medal_type = 'silver' THEN 1 ELSE 0 END) AS silver_count,\n\
    SUM(CASE WHEN rm.medal_type = 'bronze' THEN 1 ELSE 0 END) AS bronze_count\n\
\n\
FROM medals rm\n\
JOIN league_events le ON rm.event_date = le.event_date\n\
JOIN leagues l ON le.league_id = l.id\n\
WHERE rm.runner_id = @runner_id AND l.id = @league_id") set_params invoke_callback

    let medals_for_runner_overall db ~runner_id callback =
      let invoke_callback stmt =
        callback
          ~gold:(T.get_column_Int_nullable stmt 0)
          ~silver:(T.get_column_Int_nullable stmt 1)
          ~bronze:(T.get_column_Int_nullable stmt 2)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Int p runner_id;
        T.finish_params p
      in
      T.select_one db ("SELECT \n\
    SUM(CASE WHEN medal_type = 'gold' THEN 1 ELSE 0 END) AS gold,\n\
    SUM(CASE WHEN medal_type = 'silver' THEN 1 ELSE 0 END) AS silver,\n\
    SUM(CASE WHEN medal_type = 'bronze' THEN 1 ELSE 0 END) AS bronze\n\
FROM medals\n\
WHERE runner_id = @runner_id") set_params invoke_callback

  end (* module Single *)
  
  module Fold = struct
    let leagues_for_year db ~year callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_year:(T.get_column_Int stmt 1)
          ~name:(T.get_column_Text stmt 2)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Int p year;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT * FROM leagues\n\
WHERE league_year == @year\n\
ORDER BY id") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let leagues_for_name db ~league_name callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_year:(T.get_column_Int stmt 1)
          ~name:(T.get_column_Text stmt 2)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p league_name;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT * FROM leagues\n\
WHERE name = @league_name\n\
ORDER BY id") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let all_leagues db  callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_year:(T.get_column_Int stmt 1)
          ~name:(T.get_column_Text stmt 2)
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT * FROM leagues ORDER BY league_year DESC, name DESC") T.no_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let league_event_neighbors db ~input_date callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~location:(T.get_column_Text stmt 4)
          ~league_name:(T.get_column_Text stmt 5)
          ~event_link:(T.get_column_Text_nullable stmt 6)
          ~thumbnail:(T.get_column_Text_nullable stmt 7)
          ~map_info:(T.get_column_Text_nullable stmt 8)
          ~official_location:(T.get_column_Text_nullable stmt 9)
          ~links:(T.get_column_Text_nullable stmt 10)
      in
      let set_params stmt =
        let p = T.start_params stmt (2) in
        T.set_param_Text p input_date;
        T.set_param_Text p input_date;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("WITH base AS (\n\
    SELECT \n\
        le.*,\n\
        l.name        AS league_name,\n\
        ed.event_link,\n\
        ed.thumbnail,\n\
        ed.map_info,\n\
        ed.location AS official_location,\n\
        ls.links\n\
    FROM league_events le\n\
    JOIN leagues          l  ON le.league_id  = l.id\n\
    LEFT JOIN event_details   ed ON le.event_date = ed.event_date\n\
    LEFT JOIN event_map_links ls ON le.event_date = ls.event_date\n\
),\n\
before AS (\n\
    SELECT *\n\
    FROM base\n\
    WHERE event_date < @input_date\n\
    ORDER BY event_date DESC\n\
    LIMIT 1\n\
),\n\
after_or_eq AS (\n\
    SELECT *\n\
    FROM base\n\
    WHERE event_date >= @input_date\n\
    ORDER BY event_date ASC\n\
    LIMIT 1\n\
)\n\
SELECT * FROM before\n\
UNION ALL\n\
SELECT * FROM after_or_eq") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let event_details_for_year db ~year callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~event_link:(T.get_column_Text stmt 1)
          ~event_date:(T.get_column_Text stmt 2)
          ~location:(T.get_column_Text stmt 3)
          ~thumbnail:(T.get_column_Text stmt 4)
          ~map_info:(T.get_column_Text stmt 5)
          ~links:(T.get_column_Text_nullable stmt 6)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p year;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT \n\
    e.*,\n\
    l.links\n\
FROM event_details e\n\
LEFT JOIN event_map_links l\n\
ON e.event_date = l.event_date\n\
WHERE strftime('%Y', e.event_date) == @year\n\
ORDER BY e.event_date ASC") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let event_details_for_date db ~event_date callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~event_link:(T.get_column_Text stmt 1)
          ~event_date:(T.get_column_Text stmt 2)
          ~location:(T.get_column_Text stmt 3)
          ~thumbnail:(T.get_column_Text stmt 4)
          ~map_info:(T.get_column_Text stmt 5)
          ~links:(T.get_column_Text_nullable stmt 6)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p event_date;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT \n\
    e.*,\n\
    l.links\n\
FROM event_details e\n\
LEFT JOIN event_map_links l\n\
ON e.event_date = l.event_date\n\
WHERE e.event_date == @event_date") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let events_to_be_processed db  callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~location:(T.get_column_Text stmt 4)
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT le.*\n\
FROM league_events le\n\
LEFT JOIN event_stats es ON le.event_date = es.event_date\n\
WHERE es.id IS NULL\n\
ORDER BY \n\
    le.league_id ASC, \n\
    le.event_date ASC") T.no_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let events_to_be_processed_for_year db ~league_year callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~location:(T.get_column_Text stmt 4)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Int p league_year;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT le.*\n\
FROM league_events le\n\
JOIN leagues l ON le.league_id = l.id\n\
LEFT JOIN event_stats es ON le.event_date = es.event_date\n\
WHERE l.league_year = @league_year\n\
  AND es.id IS NULL\n\
ORDER BY \n\
    le.league_id ASC, \n\
    le.event_date ASC") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let courses_for_event db ~event_date callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~distance:(T.get_column_Float stmt 5)
          ~num_controls:(T.get_column_Int stmt 6)
          ~controls:(T.get_column_Text stmt 7)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p event_date;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT * FROM courses \n\
WHERE event_date = @event_date\n\
ORDER BY course_id ASC") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let stats_for_course db ~league_id ~event_date ~course_id callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~num_men:(T.get_column_Int stmt 5)
          ~num_women:(T.get_column_Int stmt 6)
          ~tilt_overall:(T.get_column_Int stmt 7)
          ~tilt_men:(T.get_column_Int stmt 8)
          ~tilt_women:(T.get_column_Int stmt 9)
          ~mistake_time_overall:(T.get_column_Int stmt 10)
          ~mistake_time_men:(T.get_column_Int stmt 11)
          ~mistake_time_women:(T.get_column_Int stmt 12)
          ~blunder_perc_overall:(T.get_column_Int stmt 13)
          ~blunder_perc_men:(T.get_column_Int stmt 14)
          ~blunder_perc_women:(T.get_column_Int stmt 15)
          ~big_mistake_perc_overall:(T.get_column_Int stmt 16)
          ~big_mistake_perc_men:(T.get_column_Int stmt 17)
          ~big_mistake_perc_women:(T.get_column_Int stmt 18)
          ~small_mistake_perc_overall:(T.get_column_Int stmt 19)
          ~small_mistake_perc_men:(T.get_column_Int stmt 20)
          ~small_mistake_perc_women:(T.get_column_Int stmt 21)
          ~most_tricky_overall:(T.get_column_Int_nullable stmt 22)
          ~most_tricky_men:(T.get_column_Int_nullable stmt 23)
          ~most_tricky_women:(T.get_column_Int_nullable stmt 24)
          ~avg_time_for_mistake_overall:(T.get_column_Int stmt 25)
          ~avg_time_for_mistake_men:(T.get_column_Int stmt 26)
          ~avg_time_for_mistake_women:(T.get_column_Int stmt 27)
          ~avg_mistake_num_overall:(T.get_column_Int stmt 28)
          ~avg_mistake_num_men:(T.get_column_Int stmt 29)
          ~avg_mistake_num_women:(T.get_column_Int stmt 30)
      in
      let set_params stmt =
        let p = T.start_params stmt (3) in
        T.set_param_Int p league_id;
        T.set_param_Text p event_date;
        T.set_param_Text p course_id;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT * FROM course_stats\n\
WHERE league_id = @league_id\n\
    AND event_date = @event_date\n\
    AND course_id = @course_id") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let all_groups db  callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~runner_id:(T.get_column_Int stmt 2)
          ~age_group_id:(T.get_column_Text stmt 3)
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT * FROM age_groups") T.no_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let results_for_course db ~league_id ~event_date ~course_id callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~runner_id:(T.get_column_Int stmt 5)
          ~time_sec:(T.get_column_Int_nullable stmt 6)
          ~start_time:(T.get_column_Int_nullable stmt 7)
          ~points:(T.get_column_Int stmt 8)
          ~pace:(T.get_column_Text_nullable stmt 9)
          ~dsq:(T.get_column_Int stmt 10)
      in
      let set_params stmt =
        let p = T.start_params stmt (3) in
        T.set_param_Int p league_id;
        T.set_param_Text p event_date;
        T.set_param_Text p course_id;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT * FROM results\n\
WHERE league_id = @league_id\n\
    AND event_date = @event_date\n\
    AND course_id = @course_id\n\
ORDER BY\n\
    dsq ASC,\n\
    time_sec ASC") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let all_runners db  callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~join_date:(T.get_column_Text stmt 1)
          ~name:(T.get_column_Text stmt 2)
          ~club:(T.get_column_Text stmt 3)
          ~gender:(T.get_column_Text stmt 4)
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT * FROM runners") T.no_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let ratings_for_course db ~course_id callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~runner_id:(T.get_column_Int stmt 5)
          ~rating:(T.get_column_Float stmt 6)
          ~rating_diff:(T.get_column_Float stmt 7)
          ~rd:(T.get_column_Float stmt 8)
          ~vol:(T.get_column_Float stmt 9)
          ~runner_name:(T.get_column_Text stmt 10)
          ~runner_club:(T.get_column_Text stmt 11)
          ~runner_gender:(T.get_column_Text stmt 12)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p course_id;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
INNER JOIN (\n\
            SELECT runner_id, MAX(event_date) AS max_date\n\
    FROM ratings\n\
    GROUP BY runner_id\n\
) latest ON r.runner_id = latest.runner_id AND r.event_date = latest.max_date\n\
WHERE r.course_id = @course_id\n\
ORDER BY r.rating DESC") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let all_latest_ratings db  callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~runner_id:(T.get_column_Int stmt 5)
          ~rating:(T.get_column_Float stmt 6)
          ~rating_diff:(T.get_column_Float stmt 7)
          ~rd:(T.get_column_Float stmt 8)
          ~vol:(T.get_column_Float stmt 9)
          ~runner_name:(T.get_column_Text stmt 10)
          ~runner_club:(T.get_column_Text stmt 11)
          ~runner_gender:(T.get_column_Text stmt 12)
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
INNER JOIN (\n\
            SELECT runner_id, MAX(event_date) AS max_date\n\
    FROM ratings\n\
    GROUP BY runner_id\n\
) latest ON r.runner_id = latest.runner_id AND r.event_date = latest.max_date") T.no_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let ratings_for_course_by_gender db ~gender ~course_id callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~runner_id:(T.get_column_Int stmt 5)
          ~rating:(T.get_column_Float stmt 6)
          ~rating_diff:(T.get_column_Float stmt 7)
          ~rd:(T.get_column_Float stmt 8)
          ~vol:(T.get_column_Float stmt 9)
          ~runner_name:(T.get_column_Text stmt 10)
          ~runner_club:(T.get_column_Text stmt 11)
          ~runner_gender:(T.get_column_Text stmt 12)
      in
      let set_params stmt =
        let p = T.start_params stmt (2) in
        T.set_param_Text p gender;
        T.set_param_Text p course_id;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
INNER JOIN (\n\
            SELECT runner_id, MAX(event_date) AS max_date\n\
    FROM ratings\n\
    GROUP BY runner_id\n\
) latest ON r.runner_id = latest.runner_id AND r.event_date = latest.max_date\n\
INNER JOIN runners rn ON r.runner_id = rn.id\n\
WHERE rn.gender = @gender AND r.course_id = @course_id\n\
ORDER BY r.rating DESC") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let rating_history_for_league_and_course db ~runner_id ~league_id ~course_id callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~runner_id:(T.get_column_Int stmt 5)
          ~rating:(T.get_column_Float stmt 6)
          ~rating_diff:(T.get_column_Float stmt 7)
          ~rd:(T.get_column_Float stmt 8)
          ~vol:(T.get_column_Float stmt 9)
          ~runner_name:(T.get_column_Text stmt 10)
          ~runner_club:(T.get_column_Text stmt 11)
          ~runner_gender:(T.get_column_Text stmt 12)
      in
      let set_params stmt =
        let p = T.start_params stmt (3) in
        T.set_param_Int p runner_id;
        T.set_param_Int p league_id;
        T.set_param_Text p course_id;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
WHERE runner_id = @runner_id \n\
    AND league_id = @league_id \n\
    AND course_id = @course_id\n\
ORDER BY event_date ASC") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let rating_history_for_course db ~runner_id ~course_id callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~runner_id:(T.get_column_Int stmt 5)
          ~rating:(T.get_column_Float stmt 6)
          ~rating_diff:(T.get_column_Float stmt 7)
          ~rd:(T.get_column_Float stmt 8)
          ~vol:(T.get_column_Float stmt 9)
          ~runner_name:(T.get_column_Text stmt 10)
          ~runner_club:(T.get_column_Text stmt 11)
          ~runner_gender:(T.get_column_Text stmt 12)
      in
      let set_params stmt =
        let p = T.start_params stmt (2) in
        T.set_param_Int p runner_id;
        T.set_param_Text p course_id;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
WHERE runner_id = @runner_id \n\
    AND course_id = @course_id\n\
ORDER BY event_date ASC") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let medal_history_for_runner db ~runner_id callback acc =
      let invoke_callback stmt =
        callback
          ~medal_type:(T.get_column_Text stmt 0)
          ~event_date:(T.get_column_Text stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~league_name:(T.get_column_Text stmt 3)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Int p runner_id;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT \n\
    rm.medal_type,\n\
    le.event_date,\n\
    le.event_nr,\n\
    l.name AS league_name\n\
FROM medals rm\n\
JOIN league_events le ON rm.event_date = le.event_date\n\
JOIN leagues l ON le.league_id = l.id\n\
WHERE rm.runner_id = @runner_id\n\
ORDER BY le.event_date ASC") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

  end (* module Fold *)
  
  module List = struct
    let leagues_for_year db ~year callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_year:(T.get_column_Int stmt 1)
          ~name:(T.get_column_Text stmt 2)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Int p year;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT * FROM leagues\n\
WHERE league_year == @year\n\
ORDER BY id") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let leagues_for_name db ~league_name callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_year:(T.get_column_Int stmt 1)
          ~name:(T.get_column_Text stmt 2)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p league_name;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT * FROM leagues\n\
WHERE name = @league_name\n\
ORDER BY id") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let all_leagues db  callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_year:(T.get_column_Int stmt 1)
          ~name:(T.get_column_Text stmt 2)
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT * FROM leagues ORDER BY league_year DESC, name DESC") T.no_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let league_event_neighbors db ~input_date callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~location:(T.get_column_Text stmt 4)
          ~league_name:(T.get_column_Text stmt 5)
          ~event_link:(T.get_column_Text_nullable stmt 6)
          ~thumbnail:(T.get_column_Text_nullable stmt 7)
          ~map_info:(T.get_column_Text_nullable stmt 8)
          ~official_location:(T.get_column_Text_nullable stmt 9)
          ~links:(T.get_column_Text_nullable stmt 10)
      in
      let set_params stmt =
        let p = T.start_params stmt (2) in
        T.set_param_Text p input_date;
        T.set_param_Text p input_date;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("WITH base AS (\n\
    SELECT \n\
        le.*,\n\
        l.name        AS league_name,\n\
        ed.event_link,\n\
        ed.thumbnail,\n\
        ed.map_info,\n\
        ed.location AS official_location,\n\
        ls.links\n\
    FROM league_events le\n\
    JOIN leagues          l  ON le.league_id  = l.id\n\
    LEFT JOIN event_details   ed ON le.event_date = ed.event_date\n\
    LEFT JOIN event_map_links ls ON le.event_date = ls.event_date\n\
),\n\
before AS (\n\
    SELECT *\n\
    FROM base\n\
    WHERE event_date < @input_date\n\
    ORDER BY event_date DESC\n\
    LIMIT 1\n\
),\n\
after_or_eq AS (\n\
    SELECT *\n\
    FROM base\n\
    WHERE event_date >= @input_date\n\
    ORDER BY event_date ASC\n\
    LIMIT 1\n\
)\n\
SELECT * FROM before\n\
UNION ALL\n\
SELECT * FROM after_or_eq") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let event_details_for_year db ~year callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~event_link:(T.get_column_Text stmt 1)
          ~event_date:(T.get_column_Text stmt 2)
          ~location:(T.get_column_Text stmt 3)
          ~thumbnail:(T.get_column_Text stmt 4)
          ~map_info:(T.get_column_Text stmt 5)
          ~links:(T.get_column_Text_nullable stmt 6)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p year;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT \n\
    e.*,\n\
    l.links\n\
FROM event_details e\n\
LEFT JOIN event_map_links l\n\
ON e.event_date = l.event_date\n\
WHERE strftime('%Y', e.event_date) == @year\n\
ORDER BY e.event_date ASC") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let event_details_for_date db ~event_date callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~event_link:(T.get_column_Text stmt 1)
          ~event_date:(T.get_column_Text stmt 2)
          ~location:(T.get_column_Text stmt 3)
          ~thumbnail:(T.get_column_Text stmt 4)
          ~map_info:(T.get_column_Text stmt 5)
          ~links:(T.get_column_Text_nullable stmt 6)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p event_date;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT \n\
    e.*,\n\
    l.links\n\
FROM event_details e\n\
LEFT JOIN event_map_links l\n\
ON e.event_date = l.event_date\n\
WHERE e.event_date == @event_date") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let events_to_be_processed db  callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~location:(T.get_column_Text stmt 4)
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT le.*\n\
FROM league_events le\n\
LEFT JOIN event_stats es ON le.event_date = es.event_date\n\
WHERE es.id IS NULL\n\
ORDER BY \n\
    le.league_id ASC, \n\
    le.event_date ASC") T.no_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let events_to_be_processed_for_year db ~league_year callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~location:(T.get_column_Text stmt 4)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Int p league_year;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT le.*\n\
FROM league_events le\n\
JOIN leagues l ON le.league_id = l.id\n\
LEFT JOIN event_stats es ON le.event_date = es.event_date\n\
WHERE l.league_year = @league_year\n\
  AND es.id IS NULL\n\
ORDER BY \n\
    le.league_id ASC, \n\
    le.event_date ASC") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let courses_for_event db ~event_date callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~distance:(T.get_column_Float stmt 5)
          ~num_controls:(T.get_column_Int stmt 6)
          ~controls:(T.get_column_Text stmt 7)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p event_date;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT * FROM courses \n\
WHERE event_date = @event_date\n\
ORDER BY course_id ASC") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let stats_for_course db ~league_id ~event_date ~course_id callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~num_men:(T.get_column_Int stmt 5)
          ~num_women:(T.get_column_Int stmt 6)
          ~tilt_overall:(T.get_column_Int stmt 7)
          ~tilt_men:(T.get_column_Int stmt 8)
          ~tilt_women:(T.get_column_Int stmt 9)
          ~mistake_time_overall:(T.get_column_Int stmt 10)
          ~mistake_time_men:(T.get_column_Int stmt 11)
          ~mistake_time_women:(T.get_column_Int stmt 12)
          ~blunder_perc_overall:(T.get_column_Int stmt 13)
          ~blunder_perc_men:(T.get_column_Int stmt 14)
          ~blunder_perc_women:(T.get_column_Int stmt 15)
          ~big_mistake_perc_overall:(T.get_column_Int stmt 16)
          ~big_mistake_perc_men:(T.get_column_Int stmt 17)
          ~big_mistake_perc_women:(T.get_column_Int stmt 18)
          ~small_mistake_perc_overall:(T.get_column_Int stmt 19)
          ~small_mistake_perc_men:(T.get_column_Int stmt 20)
          ~small_mistake_perc_women:(T.get_column_Int stmt 21)
          ~most_tricky_overall:(T.get_column_Int_nullable stmt 22)
          ~most_tricky_men:(T.get_column_Int_nullable stmt 23)
          ~most_tricky_women:(T.get_column_Int_nullable stmt 24)
          ~avg_time_for_mistake_overall:(T.get_column_Int stmt 25)
          ~avg_time_for_mistake_men:(T.get_column_Int stmt 26)
          ~avg_time_for_mistake_women:(T.get_column_Int stmt 27)
          ~avg_mistake_num_overall:(T.get_column_Int stmt 28)
          ~avg_mistake_num_men:(T.get_column_Int stmt 29)
          ~avg_mistake_num_women:(T.get_column_Int stmt 30)
      in
      let set_params stmt =
        let p = T.start_params stmt (3) in
        T.set_param_Int p league_id;
        T.set_param_Text p event_date;
        T.set_param_Text p course_id;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT * FROM course_stats\n\
WHERE league_id = @league_id\n\
    AND event_date = @event_date\n\
    AND course_id = @course_id") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let all_groups db  callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~runner_id:(T.get_column_Int stmt 2)
          ~age_group_id:(T.get_column_Text stmt 3)
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT * FROM age_groups") T.no_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let results_for_course db ~league_id ~event_date ~course_id callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~runner_id:(T.get_column_Int stmt 5)
          ~time_sec:(T.get_column_Int_nullable stmt 6)
          ~start_time:(T.get_column_Int_nullable stmt 7)
          ~points:(T.get_column_Int stmt 8)
          ~pace:(T.get_column_Text_nullable stmt 9)
          ~dsq:(T.get_column_Int stmt 10)
      in
      let set_params stmt =
        let p = T.start_params stmt (3) in
        T.set_param_Int p league_id;
        T.set_param_Text p event_date;
        T.set_param_Text p course_id;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT * FROM results\n\
WHERE league_id = @league_id\n\
    AND event_date = @event_date\n\
    AND course_id = @course_id\n\
ORDER BY\n\
    dsq ASC,\n\
    time_sec ASC") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let all_runners db  callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~join_date:(T.get_column_Text stmt 1)
          ~name:(T.get_column_Text stmt 2)
          ~club:(T.get_column_Text stmt 3)
          ~gender:(T.get_column_Text stmt 4)
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT * FROM runners") T.no_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let ratings_for_course db ~course_id callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~runner_id:(T.get_column_Int stmt 5)
          ~rating:(T.get_column_Float stmt 6)
          ~rating_diff:(T.get_column_Float stmt 7)
          ~rd:(T.get_column_Float stmt 8)
          ~vol:(T.get_column_Float stmt 9)
          ~runner_name:(T.get_column_Text stmt 10)
          ~runner_club:(T.get_column_Text stmt 11)
          ~runner_gender:(T.get_column_Text stmt 12)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p course_id;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
INNER JOIN (\n\
            SELECT runner_id, MAX(event_date) AS max_date\n\
    FROM ratings\n\
    GROUP BY runner_id\n\
) latest ON r.runner_id = latest.runner_id AND r.event_date = latest.max_date\n\
WHERE r.course_id = @course_id\n\
ORDER BY r.rating DESC") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let all_latest_ratings db  callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~runner_id:(T.get_column_Int stmt 5)
          ~rating:(T.get_column_Float stmt 6)
          ~rating_diff:(T.get_column_Float stmt 7)
          ~rd:(T.get_column_Float stmt 8)
          ~vol:(T.get_column_Float stmt 9)
          ~runner_name:(T.get_column_Text stmt 10)
          ~runner_club:(T.get_column_Text stmt 11)
          ~runner_gender:(T.get_column_Text stmt 12)
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
INNER JOIN (\n\
            SELECT runner_id, MAX(event_date) AS max_date\n\
    FROM ratings\n\
    GROUP BY runner_id\n\
) latest ON r.runner_id = latest.runner_id AND r.event_date = latest.max_date") T.no_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let ratings_for_course_by_gender db ~gender ~course_id callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~runner_id:(T.get_column_Int stmt 5)
          ~rating:(T.get_column_Float stmt 6)
          ~rating_diff:(T.get_column_Float stmt 7)
          ~rd:(T.get_column_Float stmt 8)
          ~vol:(T.get_column_Float stmt 9)
          ~runner_name:(T.get_column_Text stmt 10)
          ~runner_club:(T.get_column_Text stmt 11)
          ~runner_gender:(T.get_column_Text stmt 12)
      in
      let set_params stmt =
        let p = T.start_params stmt (2) in
        T.set_param_Text p gender;
        T.set_param_Text p course_id;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
INNER JOIN (\n\
            SELECT runner_id, MAX(event_date) AS max_date\n\
    FROM ratings\n\
    GROUP BY runner_id\n\
) latest ON r.runner_id = latest.runner_id AND r.event_date = latest.max_date\n\
INNER JOIN runners rn ON r.runner_id = rn.id\n\
WHERE rn.gender = @gender AND r.course_id = @course_id\n\
ORDER BY r.rating DESC") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let rating_history_for_league_and_course db ~runner_id ~league_id ~course_id callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~runner_id:(T.get_column_Int stmt 5)
          ~rating:(T.get_column_Float stmt 6)
          ~rating_diff:(T.get_column_Float stmt 7)
          ~rd:(T.get_column_Float stmt 8)
          ~vol:(T.get_column_Float stmt 9)
          ~runner_name:(T.get_column_Text stmt 10)
          ~runner_club:(T.get_column_Text stmt 11)
          ~runner_gender:(T.get_column_Text stmt 12)
      in
      let set_params stmt =
        let p = T.start_params stmt (3) in
        T.set_param_Int p runner_id;
        T.set_param_Int p league_id;
        T.set_param_Text p course_id;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
WHERE runner_id = @runner_id \n\
    AND league_id = @league_id \n\
    AND course_id = @course_id\n\
ORDER BY event_date ASC") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let rating_history_for_course db ~runner_id ~course_id callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_id:(T.get_column_Int stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~event_date:(T.get_column_Text stmt 3)
          ~course_id:(T.get_column_Text stmt 4)
          ~runner_id:(T.get_column_Int stmt 5)
          ~rating:(T.get_column_Float stmt 6)
          ~rating_diff:(T.get_column_Float stmt 7)
          ~rd:(T.get_column_Float stmt 8)
          ~vol:(T.get_column_Float stmt 9)
          ~runner_name:(T.get_column_Text stmt 10)
          ~runner_club:(T.get_column_Text stmt 11)
          ~runner_gender:(T.get_column_Text stmt 12)
      in
      let set_params stmt =
        let p = T.start_params stmt (2) in
        T.set_param_Int p runner_id;
        T.set_param_Text p course_id;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT r.*, rn.name AS runner_name, rn.club AS runner_club, rn.gender AS runner_gender\n\
FROM ratings r\n\
JOIN runners rn ON r.runner_id = rn.id\n\
WHERE runner_id = @runner_id \n\
    AND course_id = @course_id\n\
ORDER BY event_date ASC") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let medal_history_for_runner db ~runner_id callback =
      let invoke_callback stmt =
        callback
          ~medal_type:(T.get_column_Text stmt 0)
          ~event_date:(T.get_column_Text stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~league_name:(T.get_column_Text stmt 3)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Int p runner_id;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT \n\
    rm.medal_type,\n\
    le.event_date,\n\
    le.event_nr,\n\
    l.name AS league_name\n\
FROM medals rm\n\
JOIN league_events le ON rm.event_date = le.event_date\n\
JOIN leagues l ON le.league_id = l.id\n\
WHERE rm.runner_id = @runner_id\n\
ORDER BY le.event_date ASC") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

  end (* module List *)
end (* module DbOps *)
