(* DO NOT EDIT MANUALLY *)
(*  *)
(* generated by sqlgg <unknown> on 2026-04-10T07:27Z *)

module DbOps (T : Sqlgg_traits.M) = struct

  module IO = Sqlgg_io.Blocking

  let create_leagues db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS leagues (\n\
    id INTEGER PRIMARY KEY,\n\
    league_year INTEGER NOT NULL,\n\
    name TEXT NOT NULL\n\
)") T.no_params

  let add_league db ~id ~league_year ~name =
    let set_params stmt =
      let p = T.start_params stmt (3) in
      T.set_param_Int p id;
      T.set_param_Int p league_year;
      T.set_param_Text p name;
      T.finish_params p
    in
    T.execute db ("INSERT INTO leagues VALUES (@id,@league_year,@name)") set_params

  let leagues_for_year db ~year callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_year:(T.get_column_Int stmt 1)
        ~name:(T.get_column_Text stmt 2)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Int p year;
      T.finish_params p
    in
    T.select db ("SELECT * FROM leagues\n\
WHERE league_year == @year\n\
ORDER BY id") set_params invoke_callback

  let all_leagues db  callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~league_year:(T.get_column_Int stmt 1)
        ~name:(T.get_column_Text stmt 2)
    in
    T.select db ("SELECT * FROM leagues ORDER BY league_year DESC, name DESC") T.no_params invoke_callback

  let create_league_events db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS league_events (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
\n\
    event_date TEXT NOT NULL,\n\
    location TEXT NOT NULL\n\
)") T.no_params

  let add_league_event db ~id ~league_id ~event_nr ~event_date ~location =
    let set_params stmt =
      let p = T.start_params stmt (5) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Text p event_date;
      T.set_param_Text p location;
      T.finish_params p
    in
    T.execute db ("INSERT INTO league_events VALUES (@id,@league_id,@event_nr,@event_date,@location)") set_params

  let league_event_before db ~input_date =
    let get_row stmt =
      (T.get_column_Int stmt 0), (T.get_column_Int stmt 1), (T.get_column_Int stmt 2), (T.get_column_Text stmt 3), (T.get_column_Text stmt 4), (T.get_column_Text stmt 5)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Text p input_date;
      T.finish_params p
    in
    T.select_one_maybe db ("SELECT le.*, l.name AS league_name\n\
FROM league_events le\n\
JOIN leagues l ON le.league_id = l.id\n\
WHERE le.event_date < @input_date\n\
ORDER BY le.event_date DESC\n\
LIMIT 1") set_params get_row

  let league_event_after_or_eq db ~input_date =
    let get_row stmt =
      (T.get_column_Int stmt 0), (T.get_column_Int stmt 1), (T.get_column_Int stmt 2), (T.get_column_Text stmt 3), (T.get_column_Text stmt 4), (T.get_column_Text stmt 5)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Text p input_date;
      T.finish_params p
    in
    T.select_one_maybe db ("SELECT le.*, l.name AS league_name\n\
FROM league_events le\n\
JOIN leagues l ON le.league_id = l.id\n\
WHERE le.event_date >= @input_date\n\
ORDER BY le.event_date ASC\n\
LIMIT 1") set_params get_row

  let create_event_details db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS event_details (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
\n\
    event_link TEXT NOT NULL,\n\
                event_date TEXT NOT NULL,\n\
    location TEXT NOT NULL,\n\
    thumbnail TEXT NOT NULL,\n\
    map_info TEXT NOT NULL\n\
)") T.no_params

  let add_event_details db ~id ~event_link ~event_date ~location ~thumbnail ~map_info =
    let set_params stmt =
      let p = T.start_params stmt (6) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Text p event_link;
      T.set_param_Text p event_date;
      T.set_param_Text p location;
      T.set_param_Text p thumbnail;
      T.set_param_Text p map_info;
      T.finish_params p
    in
    T.execute db ("INSERT INTO event_details VALUES (@id,@event_link,@event_date,@location,@thumbnail,@map_info)") set_params

  let create_event_map_links db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS event_map_links (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
\n\
    event_date TEXT NOT NULL,\n\
    links TEXT NOT NULL\n\
)") T.no_params

  let add_event_map_link db ~id ~event_date ~links =
    let set_params stmt =
      let p = T.start_params stmt (3) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Text p event_date;
      T.set_param_Text p links;
      T.finish_params p
    in
    T.execute db ("INSERT INTO event_map_links VALUES (@id,@event_date,@links)") set_params

  let event_details_for_year db ~year callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~event_link:(T.get_column_Text stmt 1)
        ~event_date:(T.get_column_Text stmt 2)
        ~location:(T.get_column_Text stmt 3)
        ~thumbnail:(T.get_column_Text stmt 4)
        ~map_info:(T.get_column_Text stmt 5)
        ~links:(T.get_column_Text stmt 6)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Text p year;
      T.finish_params p
    in
    T.select db ("SELECT \n\
    e.*,\n\
    l.links\n\
FROM event_details e\n\
LEFT JOIN event_map_links l\n\
ON e.event_date = l.event_date\n\
WHERE strftime('%Y', e.event_date) == @year\n\
ORDER BY e.event_date ASC") set_params invoke_callback

  let event_details_for_date db ~event_date callback =
    let invoke_callback stmt =
      callback
        ~id:(T.get_column_Int stmt 0)
        ~event_link:(T.get_column_Text stmt 1)
        ~event_date:(T.get_column_Text stmt 2)
        ~location:(T.get_column_Text stmt 3)
        ~thumbnail:(T.get_column_Text stmt 4)
        ~map_info:(T.get_column_Text stmt 5)
        ~links:(T.get_column_Text stmt 6)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Text p event_date;
      T.finish_params p
    in
    T.select db ("SELECT \n\
    e.*,\n\
    l.links\n\
FROM event_details e\n\
LEFT JOIN event_map_links l\n\
ON e.event_date = l.event_date\n\
WHERE e.event_date == @event_date") set_params invoke_callback

  let create_event_maps db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS event_maps (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
\n\
    event_date TEXT NOT NULL,\n\
    map_key TEXT NOT NULL,\n\
    title TEXT NOT NULL,\n\
    lat FLOAT NOT NULL,\n\
    lon FLOAT NOT NULL,\n\
    image TEXT NOT NULL,\n\
    for_bikes INTEGER NOT NULL\n\
)") T.no_params

  let add_event_map db ~id ~event_date ~map_key ~title ~lat ~lon ~image ~for_bikes =
    let set_params stmt =
      let p = T.start_params stmt (8) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Text p event_date;
      T.set_param_Text p map_key;
      T.set_param_Text p title;
      T.set_param_Float p lat;
      T.set_param_Float p lon;
      T.set_param_Text p image;
      T.set_param_Int p for_bikes;
      T.finish_params p
    in
    T.execute db ("INSERT INTO event_maps VALUES (@id,@event_date,@map_key,@title,@lat,@lon,@image,@for_bikes)") set_params

  let create_event_stats db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS event_stats (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
\n\
    num_men INTEGER NOT NULL,\n\
    num_women INTEGER NOT NULL\n\
)") T.no_params

  let add_event_stats db ~id ~league_id ~event_nr ~num_men ~num_women =
    let set_params stmt =
      let p = T.start_params stmt (5) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Int p num_men;
      T.set_param_Int p num_women;
      T.finish_params p
    in
    T.execute db ("INSERT INTO event_stats VALUES (@id,@league_id,@event_nr,@num_men,@num_women)") set_params

  let create_courses db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS courses (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    course_id INTEGER NOT NULL,\n\
\n\
    course_name TEXT NOT NULL,\n\
    distance FLOAT NOT NULL,\n\
    num_controls TEXT NOT NULL,\n\
    controls TEXT NOT NULL\n\
)") T.no_params

  let add_course db ~id ~league_id ~event_nr ~course_id ~course_name ~distance ~num_controls ~controls =
    let set_params stmt =
      let p = T.start_params stmt (8) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Int p course_id;
      T.set_param_Text p course_name;
      T.set_param_Float p distance;
      T.set_param_Text p num_controls;
      T.set_param_Text p controls;
      T.finish_params p
    in
    T.execute db ("INSERT INTO courses VALUES (@id,@league_id,@event_nr,@course_id,@course_name,@distance,@num_controls,@controls)") set_params

  let create_course_stats db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS course_stats (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    course_id INTEGER NOT NULL,\n\
\n\
    num_men  INTEGER NOT NULL,\n\
    num_women  INTEGER NOT NULL,\n\
    tilt_overall  INTEGER NOT NULL,\n\
    tilt_men  INTEGER NOT NULL,\n\
    tilt_women  INTEGER NOT NULL,\n\
    mistake_time_overall  INTEGER NOT NULL,\n\
    mistake_time_men  INTEGER NOT NULL,\n\
    mistake_time_women  INTEGER NOT NULL,\n\
    blunder_perc_overall  INTEGER NOT NULL,\n\
    blunder_perc_men  INTEGER NOT NULL,\n\
    blunder_perc_women  INTEGER NOT NULL,\n\
    big_mistake_perc_overall  INTEGER NOT NULL,\n\
    big_mistake_perc_men  INTEGER NOT NULL,\n\
    big_mistake_perc_women  INTEGER NOT NULL,\n\
    small_mistake_perc_overall  INTEGER NOT NULL,\n\
    small_mistake_perc_men  INTEGER NOT NULL,\n\
    small_mistake_perc_women  INTEGER NOT NULL,\n\
    most_tricky_overall  INTEGER,\n\
    most_tricky_men  INTEGER,\n\
    most_tricky_women  INTEGER,\n\
    avg_time_for_mistake_overall  INTEGER NOT NULL,\n\
    avg_time_for_mistake_men  INTEGER NOT NULL,\n\
    avg_time_for_mistake_women  INTEGER NOT NULL,\n\
    avg_mistake_num_overall  INTEGER NOT NULL,\n\
    avg_mistake_num_men  INTEGER NOT NULL,\n\
    avg_mistake_num_women  INTEGER NOT NULL\n\
)") T.no_params

  let add_course_stats db ~id ~league_id ~event_nr ~course_id ~num_men ~num_women ~tilt_overall ~tilt_men ~tilt_women ~mistake_time_overall ~mistake_time_men ~mistake_time_women ~blunder_perc_overall ~blunder_perc_men ~blunder_perc_women ~big_mistake_perc_overall ~big_mistake_perc_men ~big_mistake_perc_women ~small_mistake_perc_overall ~small_mistake_perc_men ~small_mistake_perc_women ~most_tricky_overall ~most_tricky_men ~most_tricky_women ~avg_time_for_mistake_overall ~avg_time_for_mistake_men ~avg_time_for_mistake_women ~avg_mistake_num_overall ~avg_mistake_num_men ~avg_mistake_num_women =
    let set_params stmt =
      let p = T.start_params stmt (30) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Int p course_id;
      T.set_param_Int p num_men;
      T.set_param_Int p num_women;
      T.set_param_Int p tilt_overall;
      T.set_param_Int p tilt_men;
      T.set_param_Int p tilt_women;
      T.set_param_Int p mistake_time_overall;
      T.set_param_Int p mistake_time_men;
      T.set_param_Int p mistake_time_women;
      T.set_param_Int p blunder_perc_overall;
      T.set_param_Int p blunder_perc_men;
      T.set_param_Int p blunder_perc_women;
      T.set_param_Int p big_mistake_perc_overall;
      T.set_param_Int p big_mistake_perc_men;
      T.set_param_Int p big_mistake_perc_women;
      T.set_param_Int p small_mistake_perc_overall;
      T.set_param_Int p small_mistake_perc_men;
      T.set_param_Int p small_mistake_perc_women;
      T.set_param_Int p most_tricky_overall;
      T.set_param_Int p most_tricky_men;
      T.set_param_Int p most_tricky_women;
      T.set_param_Int p avg_time_for_mistake_overall;
      T.set_param_Int p avg_time_for_mistake_men;
      T.set_param_Int p avg_time_for_mistake_women;
      T.set_param_Int p avg_mistake_num_overall;
      T.set_param_Int p avg_mistake_num_men;
      T.set_param_Int p avg_mistake_num_women;
      T.finish_params p
    in
    T.execute db ("INSERT INTO course_stats VALUES (@id,@league_id,@event_nr,@course_id,@num_men,@num_women,@tilt_overall,@tilt_men,@tilt_women,@mistake_time_overall,@mistake_time_men,@mistake_time_women,@blunder_perc_overall,@blunder_perc_men,@blunder_perc_women,@big_mistake_perc_overall,@big_mistake_perc_men,@big_mistake_perc_women,@small_mistake_perc_overall,@small_mistake_perc_men,@small_mistake_perc_women,@most_tricky_overall,@most_tricky_men,@most_tricky_women,@avg_time_for_mistake_overall,@avg_time_for_mistake_men,@avg_time_for_mistake_women,@avg_mistake_num_overall,@avg_mistake_num_men,@avg_mistake_num_women)") set_params

  let create_age_groups db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS age_groups (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    runner_id INTEGER NOT NULL,\n\
\n\
    group_id TEXT NOT NULL\n\
)") T.no_params

  let add_age_group db ~id ~league_id ~runner_id ~group_id =
    let set_params stmt =
      let p = T.start_params stmt (4) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p runner_id;
      T.set_param_Text p group_id;
      T.finish_params p
    in
    T.execute db ("INSERT INTO age_groups VALUES (@id,@league_id,@runner_id,@group_id)") set_params

  let create_results db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS results (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    course_id INTEGER NOT NULL,\n\
    runner_id INTEGER NOT NULL,\n\
\n\
    time_sec INTEGER,\n\
    start INTEGER,\n\
    points INTEGER NOT NULL,\n\
    pace TEXT,\n\
    finished INTEGER NOT NULL\n\
)") T.no_params

  let add_result db ~id ~league_id ~event_nr ~course_id ~runner_id ~time_sec ~start ~points ~pace ~finished =
    let set_params stmt =
      let p = T.start_params stmt (10) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Int p course_id;
      T.set_param_Int p runner_id;
      T.set_param_Int p time_sec;
      T.set_param_Int p start;
      T.set_param_Int p points;
      T.set_param_Text p pace;
      T.set_param_Int p finished;
      T.finish_params p
    in
    T.execute db ("INSERT INTO results VALUES (@id,@league_id,@event_nr,@course_id,@runner_id,@time_sec,@start,@points,@pace,@finished)") set_params

  let create_result_stats db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS result_stats (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    course_id INTEGER NOT NULL,\n\
    runner_id INTEGER NOT NULL,\n\
\n\
    mistake_time INTEGER NOT NULL,\n\
    mistake_num INTEGER NOT NULL,\n\
\n\
    small_mistake_time INTEGER NOT NULL,\n\
    small_mistake_num INTEGER NOT NULL,\n\
    small_mistake_time_ratio INTEGER NOT NULL,\n\
    small_mistake_num_ratio INTEGER NOT NULL,\n\
\n\
    big_mistake_time INTEGER NOT NULL,\n\
    big_mistake_num INTEGER NOT NULL,\n\
    big_mistake_time_ratio INTEGER NOT NULL,\n\
    big_mistake_num_ratio INTEGER NOT NULL,\n\
\n\
    blunder_mistake_time INTEGER NOT NULL,\n\
    blunder_mistake_num INTEGER NOT NULL,\n\
    blunder_mistake_time_ratio INTEGER NOT NULL,\n\
    blunder_mistake_num_ratio INTEGER NOT NULL,\n\
\n\
    consecutive_mistakes INTEGER NOT NULL,\n\
    tilt_rate INTEGER NOT NULL,\n\
\n\
    mistake_cluster TEXT,\n\
    mistakes_impact TEXT,\n\
    race_execution TEXT,\n\
\n\
    best_splits INTEGER NOT NULL,\n\
    top5_splits INTEGER NOT NULL,\n\
    top10_splits INTEGER NOT NULL,\n\
    performance INTEGER NOT NULL,\n\
\n\
    overall_position INTEGER,\n\
    position_gender INTEGER,\n\
    position_group INTEGER,\n\
\n\
    potential_time INTEGER,\n\
    potential_position INTEGER\n\
)") T.no_params

  let add_result_stats db ~id ~league_id ~event_nr ~course_id ~runner_id ~mistake_time ~mistake_num ~small_mistake_time ~small_mistake_num ~small_mistake_time_ratio ~small_mistake_num_ratio ~big_mistake_time ~big_mistake_num ~big_mistake_time_ratio ~big_mistake_num_ratio ~blunder_mistake_time ~blunder_mistake_num ~blunder_mistake_time_ratio ~blunder_mistake_num_ratio ~consecutive_mistakes ~tilt_rate ~mistake_cluster ~mistakes_impact ~race_execution ~best_splits ~top5_splits ~top10_splits ~performance ~overall_position ~position_gender ~position_group ~potential_time ~potential_position =
    let set_params stmt =
      let p = T.start_params stmt (33) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Int p course_id;
      T.set_param_Int p runner_id;
      T.set_param_Int p mistake_time;
      T.set_param_Int p mistake_num;
      T.set_param_Int p small_mistake_time;
      T.set_param_Int p small_mistake_num;
      T.set_param_Int p small_mistake_time_ratio;
      T.set_param_Int p small_mistake_num_ratio;
      T.set_param_Int p big_mistake_time;
      T.set_param_Int p big_mistake_num;
      T.set_param_Int p big_mistake_time_ratio;
      T.set_param_Int p big_mistake_num_ratio;
      T.set_param_Int p blunder_mistake_time;
      T.set_param_Int p blunder_mistake_num;
      T.set_param_Int p blunder_mistake_time_ratio;
      T.set_param_Int p blunder_mistake_num_ratio;
      T.set_param_Int p consecutive_mistakes;
      T.set_param_Int p tilt_rate;
      T.set_param_Text p mistake_cluster;
      T.set_param_Text p mistakes_impact;
      T.set_param_Text p race_execution;
      T.set_param_Int p best_splits;
      T.set_param_Int p top5_splits;
      T.set_param_Int p top10_splits;
      T.set_param_Int p performance;
      T.set_param_Int p overall_position;
      T.set_param_Int p position_gender;
      T.set_param_Int p position_group;
      T.set_param_Int p potential_time;
      T.set_param_Int p potential_position;
      T.finish_params p
    in
    T.execute db ("INSERT INTO result_stats VALUES (@id,@league_id,@event_nr,@course_id,@runner_id,@mistake_time,@mistake_num,@small_mistake_time,@small_mistake_num,@small_mistake_time_ratio,@small_mistake_num_ratio,@big_mistake_time,@big_mistake_num,@big_mistake_time_ratio,@big_mistake_num_ratio,@blunder_mistake_time,@blunder_mistake_num,@blunder_mistake_time_ratio,@blunder_mistake_num_ratio,@consecutive_mistakes,@tilt_rate,@mistake_cluster,@mistakes_impact,@race_execution,@best_splits,@top5_splits,@top10_splits,@performance,@overall_position,@position_gender,@position_group,@potential_time,@potential_position)") set_params

  let create_splits db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS splits (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    course_id INTEGER NOT NULL,\n\
    runner_id INTEGER NOT NULL,\n\
    split_idx INTEGER NOT NULL,\n\
\n\
    time_sec INTEGER,\n\
    position INTEGER,\n\
    overall_time INTEGER,\n\
    overall_position INTEGER,\n\
    split_timestamp INTEGER,\n\
    mistake_time INTEGER\n\
)") T.no_params

  let add_splits db ~id ~league_id ~event_nr ~course_id ~runner_id ~split_idx ~time_sec ~position ~overall_time ~overall_position ~split_timestamp ~mistake_time =
    let set_params stmt =
      let p = T.start_params stmt (12) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Int p course_id;
      T.set_param_Int p runner_id;
      T.set_param_Int p split_idx;
      T.set_param_Int p time_sec;
      T.set_param_Int p position;
      T.set_param_Int p overall_time;
      T.set_param_Int p overall_position;
      T.set_param_Int p split_timestamp;
      T.set_param_Int p mistake_time;
      T.finish_params p
    in
    T.execute db ("INSERT INTO splits VALUES (@id,@league_id,@event_nr,@course_id,@runner_id,@split_idx,@time_sec,@position,@overall_time,@overall_position,@split_timestamp,@mistake_time)") set_params

  let create_runners db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS runners (\n\
    id INTEGER PRIMARY KEY,\n\
    name TEXT,\n\
    club TEXT,\n\
    gender TEXT NOT NULL\n\
)") T.no_params

  let create_ratings db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS ratings (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    league_id INTEGER NOT NULL,\n\
    event_nr INTEGER NOT NULL,\n\
    event_date TEXT NOT NULL,\n\
    course_id INTEGER NOT NULL,\n\
    runner_id INTEGER NOT NULL,\n\
\n\
    rating FLOAT NOT NULL,\n\
    rating_diff FLOAT NOT NULL,\n\
    rd FLOAT NOT NULL,\n\
    vol FLOAT NOT NULL\n\
)") T.no_params

  let add_rating db ~id ~league_id ~event_nr ~event_date ~course_id ~runner_id ~rating ~rating_diff ~rd ~vol =
    let set_params stmt =
      let p = T.start_params stmt (10) in
      begin match id with None -> T.set_param_null p | Some v -> T.set_param_Int p v end;
      T.set_param_Int p league_id;
      T.set_param_Int p event_nr;
      T.set_param_Text p event_date;
      T.set_param_Int p course_id;
      T.set_param_Int p runner_id;
      T.set_param_Float p rating;
      T.set_param_Float p rating_diff;
      T.set_param_Float p rd;
      T.set_param_Float p vol;
      T.finish_params p
    in
    T.execute db ("INSERT INTO ratings VALUES (@id,@league_id,@event_nr,@event_date,@course_id,@runner_id,@rating,@rating_diff,@rd,@vol)") set_params

  let create_medals db  =
    T.execute db ("CREATE TABLE IF NOT EXISTS medals (\n\
    id INTEGER PRIMARY KEY AUTOINCREMENT,\n\
    event_date TEXT NOT NULL,\n\
    course_id INTEGER NOT NULL,\n\
    runner_id INTEGER NOT NULL,\n\
    medal_type TEXT NOT NULL CHECK (medal_type IN ('gold', 'silver', 'bronze'))\n\
)") T.no_params

  let medals_for_runner_for_league db ~runner_id ~league_id =
    let get_row stmt =
      (T.get_column_Text stmt 0), (T.get_column_Int stmt 1), (T.get_column_Int stmt 2), (T.get_column_Int stmt 3)
    in
    let set_params stmt =
      let p = T.start_params stmt (2) in
      T.set_param_Int p runner_id;
      T.set_param_Int p league_id;
      T.finish_params p
    in
    T.select_one db ("SELECT \n\
    l.name AS league_name,\n\
\n\
    SUM(CASE WHEN rm.medal_type = 'gold' THEN 1 ELSE 0 END) AS gold_count,\n\
    SUM(CASE WHEN rm.medal_type = 'silver' THEN 1 ELSE 0 END) AS silver_count,\n\
    SUM(CASE WHEN rm.medal_type = 'bronze' THEN 1 ELSE 0 END) AS bronze_count\n\
\n\
FROM medals rm\n\
JOIN league_events le ON rm.event_date = le.event_date\n\
JOIN leagues l ON le.league_id = l.id\n\
\n\
WHERE rm.runner_id = @runner_id AND l.id = @league_id") set_params get_row

  let medals_for_runner_overall db ~runner_id =
    let get_row stmt =
      (T.get_column_Int stmt 0), (T.get_column_Int stmt 1), (T.get_column_Int stmt 2)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Int p runner_id;
      T.finish_params p
    in
    T.select_one db ("SELECT \n\
    SUM(CASE WHEN medal_type = 'gold' THEN 1 ELSE 0 END) AS gold,\n\
    SUM(CASE WHEN medal_type = 'silver' THEN 1 ELSE 0 END) AS silver,\n\
    SUM(CASE WHEN medal_type = 'bronze' THEN 1 ELSE 0 END) AS bronze\n\
FROM medals\n\
WHERE runner_id = @runner_id") set_params get_row

  let medal_history_for_runner db ~runner_id callback =
    let invoke_callback stmt =
      callback
        ~medal_type:(T.get_column_Text stmt 0)
        ~event_date:(T.get_column_Text stmt 1)
        ~event_nr:(T.get_column_Int stmt 2)
        ~league_name:(T.get_column_Text stmt 3)
    in
    let set_params stmt =
      let p = T.start_params stmt (1) in
      T.set_param_Int p runner_id;
      T.finish_params p
    in
    T.select db ("SELECT \n\
    rm.medal_type,\n\
    le.event_date,\n\
    le.event_nr,\n\
    l.name AS league_name\n\
FROM medals rm\n\
JOIN league_events le ON rm.event_date = le.event_date\n\
JOIN leagues l ON le.league_id = l.id\n\
WHERE rm.runner_id = @runner_id\n\
ORDER BY le.event_date ASC") set_params invoke_callback

  module Fold = struct
    let leagues_for_year db ~year callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_year:(T.get_column_Int stmt 1)
          ~name:(T.get_column_Text stmt 2)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Int p year;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT * FROM leagues\n\
WHERE league_year == @year\n\
ORDER BY id") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let all_leagues db  callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_year:(T.get_column_Int stmt 1)
          ~name:(T.get_column_Text stmt 2)
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT * FROM leagues ORDER BY league_year DESC, name DESC") T.no_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let event_details_for_year db ~year callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~event_link:(T.get_column_Text stmt 1)
          ~event_date:(T.get_column_Text stmt 2)
          ~location:(T.get_column_Text stmt 3)
          ~thumbnail:(T.get_column_Text stmt 4)
          ~map_info:(T.get_column_Text stmt 5)
          ~links:(T.get_column_Text stmt 6)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p year;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT \n\
    e.*,\n\
    l.links\n\
FROM event_details e\n\
LEFT JOIN event_map_links l\n\
ON e.event_date = l.event_date\n\
WHERE strftime('%Y', e.event_date) == @year\n\
ORDER BY e.event_date ASC") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let event_details_for_date db ~event_date callback acc =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~event_link:(T.get_column_Text stmt 1)
          ~event_date:(T.get_column_Text stmt 2)
          ~location:(T.get_column_Text stmt 3)
          ~thumbnail:(T.get_column_Text stmt 4)
          ~map_info:(T.get_column_Text stmt 5)
          ~links:(T.get_column_Text stmt 6)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p event_date;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT \n\
    e.*,\n\
    l.links\n\
FROM event_details e\n\
LEFT JOIN event_map_links l\n\
ON e.event_date = l.event_date\n\
WHERE e.event_date == @event_date") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

    let medal_history_for_runner db ~runner_id callback acc =
      let invoke_callback stmt =
        callback
          ~medal_type:(T.get_column_Text stmt 0)
          ~event_date:(T.get_column_Text stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~league_name:(T.get_column_Text stmt 3)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Int p runner_id;
        T.finish_params p
      in
      let r_acc = ref acc in
      IO.(>>=) (T.select db ("SELECT \n\
    rm.medal_type,\n\
    le.event_date,\n\
    le.event_nr,\n\
    l.name AS league_name\n\
FROM medals rm\n\
JOIN league_events le ON rm.event_date = le.event_date\n\
JOIN leagues l ON le.league_id = l.id\n\
WHERE rm.runner_id = @runner_id\n\
ORDER BY le.event_date ASC") set_params (fun x -> r_acc := invoke_callback x !r_acc))
      (fun () -> IO.return !r_acc)

  end (* module Fold *)
  
  module List = struct
    let leagues_for_year db ~year callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_year:(T.get_column_Int stmt 1)
          ~name:(T.get_column_Text stmt 2)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Int p year;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT * FROM leagues\n\
WHERE league_year == @year\n\
ORDER BY id") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let all_leagues db  callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~league_year:(T.get_column_Int stmt 1)
          ~name:(T.get_column_Text stmt 2)
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT * FROM leagues ORDER BY league_year DESC, name DESC") T.no_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let event_details_for_year db ~year callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~event_link:(T.get_column_Text stmt 1)
          ~event_date:(T.get_column_Text stmt 2)
          ~location:(T.get_column_Text stmt 3)
          ~thumbnail:(T.get_column_Text stmt 4)
          ~map_info:(T.get_column_Text stmt 5)
          ~links:(T.get_column_Text stmt 6)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p year;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT \n\
    e.*,\n\
    l.links\n\
FROM event_details e\n\
LEFT JOIN event_map_links l\n\
ON e.event_date = l.event_date\n\
WHERE strftime('%Y', e.event_date) == @year\n\
ORDER BY e.event_date ASC") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let event_details_for_date db ~event_date callback =
      let invoke_callback stmt =
        callback
          ~id:(T.get_column_Int stmt 0)
          ~event_link:(T.get_column_Text stmt 1)
          ~event_date:(T.get_column_Text stmt 2)
          ~location:(T.get_column_Text stmt 3)
          ~thumbnail:(T.get_column_Text stmt 4)
          ~map_info:(T.get_column_Text stmt 5)
          ~links:(T.get_column_Text stmt 6)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Text p event_date;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT \n\
    e.*,\n\
    l.links\n\
FROM event_details e\n\
LEFT JOIN event_map_links l\n\
ON e.event_date = l.event_date\n\
WHERE e.event_date == @event_date") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

    let medal_history_for_runner db ~runner_id callback =
      let invoke_callback stmt =
        callback
          ~medal_type:(T.get_column_Text stmt 0)
          ~event_date:(T.get_column_Text stmt 1)
          ~event_nr:(T.get_column_Int stmt 2)
          ~league_name:(T.get_column_Text stmt 3)
      in
      let set_params stmt =
        let p = T.start_params stmt (1) in
        T.set_param_Int p runner_id;
        T.finish_params p
      in
      let r_acc = ref [] in
      IO.(>>=) (T.select db ("SELECT \n\
    rm.medal_type,\n\
    le.event_date,\n\
    le.event_nr,\n\
    l.name AS league_name\n\
FROM medals rm\n\
JOIN league_events le ON rm.event_date = le.event_date\n\
JOIN leagues l ON le.league_id = l.id\n\
WHERE rm.runner_id = @runner_id\n\
ORDER BY le.event_date ASC") set_params (fun x -> r_acc := invoke_callback x :: !r_acc))
      (fun () -> IO.return (List.rev !r_acc))

  end (* module List *)
end (* module DbOps *)
